'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface, Sequelize) {
    /**
     * Add seed commands here.
     *
     * Example:
     * await queryInterface.bulkInsert('People', [{
     *   name: 'John Doe',
     *   isBetaMember: false
     * }], {});
    */
     await queryInterface.bulkInsert("Users", [
        {
          email: 'oainger0@craigslist.org',
          gender: 'Female',
          password: 'KcAk6Mrg7DRM',
          role: 'Construction Worker',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          email: 'hblything1@de.vu',
          gender: 'Female',
          password: 'QLXkU4wnRVbh',
          role: 'Engineer',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          email: 'sivermee2@vkontakte.ru',
          gender: 'Male',
          password: 'cQQ0flW',
          role: 'Architect',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          email: 'agreenan3@barnesandnoble.com',
          gender: 'Female',
          password: 'fk3GyIGQm',
          role: 'Electrician',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          email: 'sthirst4@blog.com',
          gender: 'Male',
          password: 'rRbsjJGFMq57',
          role: 'Construction Foreman',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          email: 'loak5@nifty.com',
          gender: 'Female',
          password: '46sy8hp1eJ',
          role: 'Estimator',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          email: 'ebroadey6@guardian.co.uk',
          gender: 'Male',
          password: 'YkEXnE',
          role: 'Subcontractor',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          email: 'dtoupe7@surveymonkey.com',
          gender: 'Female',
          password: 'QvhyaX',
          role: 'Engineer',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          email: 'jborsnall8@mediafire.com',
          gender: 'Male',
          password: 'rFEoyMIhq3mF',
          role: 'Surveyor',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          email: 'cbogace9@jigsy.com',
          gender: 'Male',
          password: 'nePyrtWqBf',
          role: 'Construction Worker',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          email: 'ibradnecka@clickbank.net',
          gender: 'Female',
          password: 'LSXxJK',
          role: 'Estimator',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          email: 'dwoodrooffeb@purevolume.com',
          gender: 'Female',
          password: 'IdyhrRQZ718W',
          role: 'Supervisor',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          email: 'amooresc@wikispaces.com',
          gender: 'Female',
          password: 'RDrCEPDuJ',
          role: 'Engineer',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          email: 'kknightd@deliciousdays.com',
          gender: 'Male',
          password: 'zKKphzIdn',
          role: 'Engineer',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          email: 'bharrisse@delicious.com',
          gender: 'Male',
          password: 'RSWYsH240nj',
          role: 'Construction Foreman',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          email: 'jdruryf@unc.edu',
          gender: 'Male',
          password: 'djBYiXGePym',
          role: 'Architect',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          email: 'drevang@yellowpages.com',
          gender: 'Male',
          password: 'pU0vIZ5HeZa',
          role: 'Construction Manager',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          email: 'cbaldockh@typepad.com',
          gender: 'Male',
          password: 'wf8GZ2zHkK',
          role: 'Construction Foreman',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          email: 'hdobrowskii@usnews.com',
          gender: 'Male',
          password: 'ylquO3oCuD',
          role: 'Electrician',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          email: 'lwalewskij@domainmarket.com',
          gender: 'Genderfluid',
          password: 'PoSJTqDJkJu',
          role: 'Surveyor',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          email: 'ovanyatink@hugedomains.com',
          gender: 'Female',
          password: 'HWg7m2l3p',
          role: 'Construction Worker',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          email: 'emacbethl@tripod.com',
          gender: 'Female',
          password: 'DW1WhUg416',
          role: 'Subcontractor',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          email: 'isiemonm@washingtonpost.com',
          gender: 'Male',
          password: 'RcN8UVPG',
          role: 'Electrician',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          email: 'rforgann@linkedin.com',
          gender: 'Male',
          password: 'qanYYdN',
          role: 'Construction Expeditor',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          email: 'vaggiso@usgs.gov',
          gender: 'Male',
          password: '101IqYhQEu',
          role: 'Architect',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          email: 'mstowtep@ezinearticles.com',
          gender: 'Female',
          password: 'wzrJ5FOS',
          role: 'Supervisor',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          email: 'bgrieveq@ycombinator.com',
          gender: 'Female',
          password: 'Wl7DxU',
          role: 'Electrician',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          email: 'mcluneyr@instagram.com',
          gender: 'Female',
          password: 'XfqCxSx',
          role: 'Electrician',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        
        {
            email: 'scampling@people.com.cn',
            gender: 'Male',
            password: 'HPA7rBeO5z4z',
            role: 'Subcontractor',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'sflavellet@msn.com',
            gender: 'Female',
            password: 'XcqMCe8l08',
            role: 'Estimator',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'rtrassu@wiley.com',
            gender: 'Male',
            password: 'cjpwrYt',
            role: 'Engineer',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'eogelbev@youtu.be',
            gender: 'Female',
            password: 'quXBIavRSi',
            role: 'Project Manager',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'vwhittenburyw@weather.com',
            gender: 'Female',
            password: '2TkaD2B',
            role: 'Engineer',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'jcoakleyx@booking.com',
            gender: 'Female',
            password: '8npHDaZeC',
            role: 'Construction Manager',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'cdysarty@gov.uk',
            gender: 'Female',
            password: 'vcYRsxv0',
            role: 'Project Manager',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'kyeelesz@ted.com',
            gender: 'Male',
            password: 'mfCgAgQSQ',
            role: 'Engineer',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'gdallinder10@wikipedia.org',
            gender: 'Male',
            password: 'dlC0FP6ye',
            role: 'Subcontractor',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'jchaim11@tmall.com',
            gender: 'Male',
            password: 's2o6Wn889U',
            role: 'Architect',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'mczapla12@mysql.com',
            gender: 'Male',
            password: 'CMzhg3mf',
            role: 'Estimator',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'jmiddle13@sohu.com',
            gender: 'Male',
            password: 'uYomHw1T',
            role: 'Construction Manager',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'mjodrelle14@reddit.com',
            gender: 'Genderqueer',
            password: 'TjvO7Lu',
            role: 'Electrician',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'nvanetti15@hubpages.com',
            gender: 'Female',
            password: 'JCndXgKlpOVz',
            role: 'Construction Foreman',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'porbell16@mit.edu',
            gender: 'Female',
            password: 'D8iv4d7u',
            role: 'Engineer',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'ggabbatiss17@sun.com',
            gender: 'Female',
            password: 'VLahPUeY',
            role: 'Electrician',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'asterricks18@cdbaby.com',
            gender: 'Female',
            password: 'u9IYZr',
            role: 'Construction Foreman',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'skibbee19@hatena.ne.jp',
            gender: 'Male',
            password: '6hhuUZI',
            role: 'Construction Foreman',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'mgullick1a@google.com.br',
            gender: 'Male',
            password: '5Um7pk',
            role: 'Subcontractor',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'hpebworth1b@flickr.com',
            gender: 'Male',
            password: 'zLY23wqE',
            role: 'Estimator',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'ematterface1c@hud.gov',
            gender: 'Female',
            password: 'IqXMqHX1dqZI',
            role: 'Construction Manager',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'bmacneilage1d@photobucket.com',
            gender: 'Female',
            password: 'jOn56QwXu0',
            role: 'Construction Manager',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'scharlo1e@columbia.edu',
            gender: 'Male',
            password: 'XwOXpF2o',
            role: 'Estimator',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'egeelan1f@reverbnation.com',
            gender: 'Male',
            password: 'eo8o49n',
            role: 'Construction Worker',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'tnegro1g@businessinsider.com',
            gender: 'Female',
            password: 'msbmE7VYO',
            role: 'Construction Foreman',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'abarette1h@economist.com',
            gender: 'Male',
            password: 'pJhz9oD',
            role: 'Construction Worker',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'gwarrier1i@alexa.com',
            gender: 'Male',
            password: 'vALnpHEe5Ls',
            role: 'Electrician',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'lridge1j@mit.edu',
            gender: 'Male',
            password: 'CxQ0xKCeusmx',
            role: 'Construction Manager',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'bwelldrake1k@lulu.com',
            gender: 'Male',
            password: 'TUpIGkydUS5',
            role: 'Construction Manager',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'fmoncey1l@is.gd',
            gender: 'Male',
            password: 'caxRTR',
            role: 'Surveyor',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'codogherty1m@cnn.com',
            gender: 'Female',
            password: 'uaxexy7K',
            role: 'Construction Foreman',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'aflaubert1n@lycos.com',
            gender: 'Male',
            password: 'BLobMX49FfOe',
            role: 'Construction Expeditor',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'grattery1o@unblog.fr',
            gender: 'Bigender',
            password: 'R0vX8qB',
            role: 'Subcontractor',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'nmcelory1p@purevolume.com',
            gender: 'Agender',
            password: '0rodhPg',
            role: 'Architect',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'bmattiassi1q@discovery.com',
            gender: 'Female',
            password: 'cgIWWaui6Eto',
            role: 'Electrician',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'jjenking1r@lycos.com',
            gender: 'Female',
            password: 'RKQ0YcsD0Q',
            role: 'Estimator',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'rsartain1s@diigo.com',
            gender: 'Male',
            password: 'BnVh8nIPoFz',
            role: 'Estimator',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'eandreas1t@bing.com',
            gender: 'Male',
            password: '02xcGrtP',
            role: 'Construction Worker',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'elilleman1u@nhs.uk',
            gender: 'Male',
            password: 'M069bmTA',
            role: 'Construction Foreman',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'jbachs1v@tumblr.com',
            gender: 'Male',
            password: '0dhxcWTlqI',
            role: 'Project Manager',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'sslayton1w@webeden.co.uk',
            gender: 'Genderfluid',
            password: 'fSoZFZ1f',
            role: 'Construction Foreman',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'rwilby1x@stumbleupon.com',
            gender: 'Male',
            password: '1Eis0oPLtZa',
            role: 'Construction Worker',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'aspreckley1y@eventbrite.com',
            gender: 'Male',
            password: '9UwgSi',
            role: 'Construction Foreman',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'cgorghetto1z@amazon.com',
            gender: 'Male',
            password: '9iunBFGj',
            role: 'Project Manager',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'ctreuge20@geocities.jp',
            gender: 'Male',
            password: 'RfRfdUe',
            role: 'Construction Foreman',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'bsavage21@about.com',
            gender: 'Female',
            password: 'OpUmD57qr3',
            role: 'Project Manager',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'nfrift22@bizjournals.com',
            gender: 'Female',
            password: 'OuoSRXNL02q',
            role: 'Subcontractor',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'lbranton23@nature.com',
            gender: 'Non-binary',
            password: 'tp8Nh6Q',
            role: 'Architect',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'dworvill24@utexas.edu',
            gender: 'Female',
            password: 'wqgonO',
            role: 'Construction Worker',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'bbilling25@shop-pro.jp',
            gender: 'Male',
            password: 'deh5cBZ',
            role: 'Engineer',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'tdelahaye26@statcounter.com',
            gender: 'Female',
            password: 'wIsr5g',
            role: 'Engineer',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'jseath27@cornell.edu',
            gender: 'Male',
            password: 'kq81gRLpMOKJ',
            role: 'Construction Expeditor',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'votoole28@friendfeed.com',
            gender: 'Polygender',
            password: 'eui66Ct23z',
            role: 'Project Manager',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'kcortez29@hao123.com',
            gender: 'Male',
            password: 'IW9jHyFWHC',
            role: 'Electrician',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'coldford2a@scientificamerican.com',
            gender: 'Male',
            password: 'pkZ8BZ58',
            role: 'Surveyor',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'kdoorbar2b@si.edu',
            gender: 'Female',
            password: '0t024J',
            role: 'Engineer',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'dmizen2c@berkeley.edu',
            gender: 'Female',
            password: 'f1KdDMMjS',
            role: 'Project Manager',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'waldred2d@thetimes.co.uk',
            gender: 'Female',
            password: 'yVNQzjaQ',
            role: 'Subcontractor',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'nclulee2e@cloudflare.com',
            gender: 'Female',
            password: 'RbqPLdCAgn',
            role: 'Architect',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'rdanielsson2f@opera.com',
            gender: 'Male',
            password: 'faECcaM',
            role: 'Electrician',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'ehailwood2g@shareasale.com',
            gender: 'Non-binary',
            password: 'onZHOEmlLc',
            role: 'Architect',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'aanyon2h@shareasale.com',
            gender: 'Male',
            password: 'QfmF0xdT',
            role: 'Construction Worker',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'rvasic2i@ihg.com',
            gender: 'Male',
            password: 'gTLp0Woas',
            role: 'Electrician',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'rzarb2j@pcworld.com',
            gender: 'Male',
            password: 'C1ZmRFsrG2',
            role: 'Subcontractor',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'tvennart2k@google.it',
            gender: 'Male',
            password: 'xYYRAKf1eFk',
            role: 'Subcontractor',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'nstuther2l@google.it',
            gender: 'Female',
            password: 'aSpkH8',
            role: 'Surveyor',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'hlotterington2m@ed.gov',
            gender: 'Female',
            password: 'HLur8P0',
            role: 'Project Manager',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'gkeys2n@netvibes.com',
            gender: 'Female',
            password: 'AvGmAuf1b',
            role: 'Estimator',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'tspedding2o@sciencedirect.com',
            gender: 'Female',
            password: 'gceCxisIrK1P',
            role: 'Construction Foreman',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'cborrill2p@sciencedirect.com',
            gender: 'Male',
            password: 'L38dNYJaR6F',
            role: 'Project Manager',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'ceard2q@china.com.cn',
            gender: 'Female',
            password: '6zZaAQONzaDl',
            role: 'Supervisor',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
          {
            email: 'sduligall2r@washington.edu',
            gender: 'Male',
            password: '6VHZvc2E',
            role: 'Engineer',
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        
        
        



        
  
  ], {});
    
  },

  async down (queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  }
};
