"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    /**
     * Add seed commands here.
     *
     * Example:
     * await queryInterface.bulkInsert('People', [{
     *   name: 'John Doe',
     *   isBetaMember: false
     * }], {});
     */
    await queryInterface.bulkInsert(
      "Movies",
      [
        

       {
        title: 'Reckless',
        genres: 'Comedy|Drama|Romance',
        year: 2001,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'When a Man Loves a Woman',
        genres: 'Drama|Romance',
        year: 1995,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Creature',
        genres: 'Documentary',
        year: 1997,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Sex and Zen (Rou pu Tuan zhi tou Qing bao Jian)',
        genres: 'Action|Adventure|Comedy|Fantasy',
        year: 2007,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Des roses en hiver',
        genres: 'Drama',
        year: 2007,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'The Magical Legend of the Leprechauns',
        genres: 'Adventure|Children|Comedy|Fantasy|Romance',
        year: 2010,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Marilena de la P7',
        genres: 'Drama|Fantasy',
        year: 1984,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Battle of Algiers, The (La battaglia di Algeri)',
        genres: 'Drama|War',
        year: 2012,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Winning of Barbara Worth, The',
        genres: 'Drama|Romance|Western',
        year: 2009,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Beijing Taxi',
        genres: 'Documentary',
        year: 1993,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: `Pleasure at Her Majesty's`,
        genres: 'Comedy|Documentary',
        year: 2009,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Gang Related',
        genres: 'Crime',
        year: 1993,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Bird of Paradise',
        genres: 'Adventure|Drama|Romance',
        year: 1990,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Man Behind the Gun, The',
        genres: 'Western',
        year: 1993,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'William S. Burroughs: A Man Within',
        genres: 'Documentary',
        year: 1995,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Half a Loaf of Kung Fu (Dian zhi gong fu gan chian chan)',
        genres: 'Action|Comedy',
        year: 2006,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Otaku',
        genres: 'Documentary',
        year: 2004,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Repeaters',
        genres: 'Action|Drama',
        year: 2009,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Party Monster',
        genres: 'Documentary',
        year: 2007,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Two Days, One Night (Deux jours, une nuit)',
        genres: 'Drama',
        year: 2009,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'To Be or Not to Be',
        genres: 'Comedy|Drama|War',
        year: 2011,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Good Student, The (Mr. Gibb)',
        genres: 'Comedy',
        year: 1986,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Synth Britannia',
        genres: 'Documentary',
        year: 1995,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Skenbart: En film om tσg',
        genres: 'Comedy',
        year: 1993,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'The Improv: 50 Years Behind the Brick Wall',
        genres: 'Comedy|Documentary',
        year: 2007,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Naan Kadavul',
        genres: 'Action|Drama|Mystery',
        year: 2011,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Fitzcarraldo',
        genres: 'Adventure|Drama',
        year: 2004,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Liam',
        genres: 'Drama',
        year: 2010,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'You, Me and Dupree',
        genres: 'Comedy',
        year: 2012,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Monkey Business',
        genres: 'Comedy',
        year: 2012,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Run Sister Run!',
        genres: 'Drama',
        year: 2006,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Police Story (Ging chaat goo si)',
        genres: 'Action|Comedy|Crime|Thriller',
        year: 1991,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Come Drink with Me (Da zui xia)',
        genres: 'Action|Adventure|Crime',
        year: 2006,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Libre Θchange',
        genres: 'Comedy',
        year: 2009,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Little Monsters',
        genres: 'Comedy',
        year: 2005,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Hunter, The',
        genres: 'Action|Thriller',
        year: 2009,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Bite the Bullet',
        genres: 'Action|Adventure|Western',
        year: 1994,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Praying with Lior',
        genres: 'Documentary',
        year: 2008,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'State Fair',
        genres: 'Comedy|Drama|Romance',
        year: 1997,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Ursul',
        genres: 'Comedy|Drama',
        year: 1996,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'In Fear',
        genres: 'Thriller',
        year: 2000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Hamlet',
        genres: 'Drama',
        year: 2009,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Lights Out',
        genres: 'Drama|Mystery|Thriller',
        year: 2001,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Tommy',
        genres: 'Drama|Musical',
        year: 2001,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '61*',
        genres: 'Drama',
        year: 2010,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Black Sunday (La maschera del demonio)',
        genres: 'Horror',
        year: 2003,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Run Sister Run!',
        genres: 'Drama',
        year: 2003,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Atomic States of America, The',
        genres: 'Documentary',
        year: 1992,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: '2046',
        genres: 'Drama|Fantasy|Romance|Sci-Fi',
        year: 2006,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Piano in a Factory, The (Gang de qin)',
        genres: 'Comedy|Drama|Musical',
        year: 2005,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Marc Maron: Thinky Pain',
        genres: 'Comedy',
        year: 1995,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Year Zero: The Silent Death of Cambodia',
        genres: 'Documentary',
        year: 2005,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Valley of the Bees (┌dolφ vcel)',
        genres: 'Drama',
        year: 1994,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Spider-Man 2',
        genres: 'Action|Adventure|Sci-Fi|IMAX',
        year: 2006,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Sin Retorno',
        genres: 'Drama|Thriller',
        year: 2005,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Harder They Fall, The',
        genres: 'Drama|Film-Noir',
        year: 1990,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Ingrid',
        genres: 'Drama',
        year: 1994,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'While You Were Sleeping',
        genres: 'Comedy|Romance',
        year: 1990,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Experimenter',
        genres: 'Drama',
        year: 1992,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Or (a.k.a. My Treasure)',
        genres: 'Drama',
        year: 1997,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Perfume',
        genres: 'Comedy|Drama',
        year: 1989,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Wonder Boys',
        genres: 'Comedy|Drama',
        year: 1998,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Young T÷rless, The (Junge T÷rless, Der)',
        genres: 'Drama',
        year: 1983,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Conversation Piece (Gruppo di famiglia in un interno)',
        genres: 'Drama',
        year: 2010,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Clean and Sober',
        genres: 'Drama',
        year: 2004,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Michael Jackson's This Is It",
        genres: 'Documentary|Musical|IMAX',
        year: 1999,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Napoleon and Samantha',
        genres: 'Adventure|Drama',
        year: 2000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Last Real Men, The (Die letzten MΣnner)',
        genres: 'Documentary',
        year: 2003,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'B. Monkey',
        genres: 'Crime|Romance|Thriller',
        year: 2000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Everything or Nothing: The Untold Story of 007',
        genres: 'Documentary',
        year: 2009,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Operation Crossbow',
        genres: 'Action|Adventure|War',
        year: 2004,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Tere Naam',
        genres: 'Romance',
        year: 2003,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Jay And Silent Bob's Super Groovy Cartoon Movie",
        genres: '(no genres listed)',
        year: 1989,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Sex and Zen (Rou pu Tuan zhi tou Qing bao Jian)',
        genres: 'Action|Adventure|Comedy|Fantasy',
        year: 2009,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Korso',
        genres: 'Drama',
        year: 2007,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Booty Call',
        genres: 'Comedy|Romance',
        year: 2007,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'In the Mirror of Maya Deren (Im Spiegel der Maya Deren)',
        genres: 'Documentary',
        year: 2012,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Maid to Order',
        genres: 'Comedy|Fantasy',
        year: 1995,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Alice (Neco z Alenky)',
        genres: 'Animation|Fantasy|Mystery',
        year: 2011,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Zotz!',
        genres: 'Comedy|Fantasy|Horror',
        year: 2007,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Hero (Ying xiong)',
        genres: 'Action|Adventure|Drama',
        year: 2012,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Bed & Board (Domicile conjugal)',
        genres: 'Comedy|Drama',
        year: 1999,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Nature of the Beast, The',
        genres: 'Crime|Horror|Mystery|Thriller',
        year: 1986,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Odgrobadogroba',
        genres: 'Comedy|Drama',
        year: 1997,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Teen Spirit',
        genres: 'Comedy',
        year: 2006,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Ghost of Frankenstein, The',
        genres: 'Horror',
        year: 2013,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Wadjda',
        genres: 'Drama',
        year: 2002,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Blackout',
        genres: 'Action|Thriller',
        year: 1996,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Secret of Moonacre, The',
        genres: 'Adventure|Fantasy|Romance',
        year: 2008,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Mean Guns',
        genres: 'Action|Crime|Thriller',
        year: 1986,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Pillow Talk',
        genres: 'Comedy|Musical|Romance',
        year: 1999,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Fur: An Imaginary Portrait of Diane Arbus',
        genres: 'Drama|Fantasy|Romance',
        year: 2010,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Lonely Guy, The',
        genres: 'Comedy',
        year: 2008,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Heavy Metal',
        genres: 'Action|Adventure|Animation|Horror|Sci-Fi',
        year: 2007,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Bride Wars',
        genres: 'Comedy|Romance',
        year: 1989,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'In Your Hands',
        genres: 'Drama',
        year: 2002,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Lucky Jordan',
        genres: 'Comedy|Crime|Drama',
        year: 2012,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Mostly Martha (Bella Martha)',
        genres: 'Comedy|Drama|Romance',
        year: 2002,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Quebrando o Tabu',
        genres: 'Documentary',
        year: 2011,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Outlaw Josey Wales, The',
        genres: 'Action|Adventure|Drama|Thriller|Western',
        year: 2006,
        createdAt: new Date(),
        updatedAt: new Date(),
      }









        
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  },
};
